<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Image\Assets\oscar_fms.ico</ApplicationIcon>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dtos\**" />
    <Compile Remove="Image\工具機-icon\**" />
    <Compile Remove="Image\控制單元\**" />
    <EmbeddedResource Remove="Dtos\**" />
    <EmbeddedResource Remove="Image\工具機-icon\**" />
    <EmbeddedResource Remove="Image\控制單元\**" />
    <None Remove="Dtos\**" />
    <None Remove="Image\工具機-icon\**" />
    <None Remove="Image\控制單元\**" />
    <Page Remove="Dtos\**" />
    <Page Remove="Image\工具機-icon\**" />
    <Page Remove="Image\控制單元\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Image\ControlUnit\06-1-lightbulbOn.png" />
    <None Remove="Image\ControlUnit\06-2-lightbulbOff.png" />
    <None Remove="Image\MachineIcons\03-.png" />
    <None Remove="Image\MachineIcons\04-.png" />
    <None Remove="Image\MachineIcons\05-.png" />
    <None Remove="Image\MachineIcons\07-.png" />
    <None Remove="Image\MachineIcons\08-.png" />
    <None Remove="Image\MachineIcons\09-.png" />
    <None Remove="Image\MachineIcons\CMM.png" />
	<None Remove="Image\MachineIcons\CNC.png" />
    <None Remove="Image\MachineIcons\EDM.png" />
    <None Remove="Image\MachineIcons\EX430.png" />
    <None Remove="Image\MachineIcons\FMS.png" />
    <None Remove="Image\MachineIcons\ICG-2Z-NC.png" />
    <None Remove="Image\MachineIcons\UH500.png" />
    <None Remove="Image\MachineIcons\long-track.png" />
    <None Remove="Image\MachineIcons\Magzine.png" />
    <None Remove="Image\MachineIcons\Robot.png" />
    <None Remove="Image\MachineIcons\RobotOff.png" />
    <None Remove="Image\MachineIcons\short-track.png" />
    <None Remove="Image\MachineIcons\ZNC.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Image\Assets\oscar_fms.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="MaterialDesignThemes.MahApps" Version="5.2.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="MongoDB.Bson" Version="3.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Image\ControlUnit\06-1-lightbulbOn.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\ControlUnit\06-2-lightbulbOff.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
	  <Resource Include="Image\MachineIcons\CMM.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Image\MachineIcons\CNC.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\EDM.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\EX430.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\FMS.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\ICG-2Z-NC.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\UH500.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\long-track.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\Magzine.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\Robot.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\03-.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\04-.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\05-.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\07-.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\08-.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\09-.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\RobotOff.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\short-track.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Image\MachineIcons\ZNC.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AttachedProperties\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Language\Strings.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>



</Project>
